---
title: '`r title`'
output: 
    github_document:
        toc: true
        toc_depth: 4
date: '`r format(Sys.time(), "%d %B %Y %I:%M %p %Z")`'
---
```{r, setup_states, include=FALSE}
knitr::opts_chunk$set(out.width = 4800,  fig.width = 12, fig.asp=0.62,  dev = 'svg') 
knitr::opts_chunk$set(echo = TRUE)
```

Covid deaths, positive tests, and hospitalizations by state from covidtracking.com https://covidtracking.com")


### Deaths
```{r, plot_state_deaths, echo=FALSE, results='hide', message=FALSE,warning=FALSE}
   print(p_deaths_liner)
   print(p_deaths)
   print(p_deltaDeaths)
   print(p_deathsPerLinear)
   print (p_deathsPer)
   print(p_deltaDeathsPer)
```
 
### Tests

```{r, plot_state_tests, echo=FALSE, results='hide', message=FALSE,warning=FALSE}
   print(p_positives)
   print(p_positive_fraction)
   print(p_positivesPer)
   print (p_deltaPositivesPer)
   print(p_total_tests)
   print(p_total_tests_per)
``` 

 
### Hospitalizations


```{r, plot_state_hosp, echo=FALSE, results='hide', message=FALSE,warning=FALSE}

   print (p_hosp)
   print(p_hospPer)
```


